# Generated by Django 6.0.2 on 2026-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_remove_item_status_item_atualmente_emprestado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
