# Generated by Django 6.0.2 on 2026-02-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('numero', models.CharField(max_length=11, verbose_name='Número de celular (DDD e números apenas)')),
            ],
        ),
    ]
