# Generated by Django 6.0.2 on 2026-02-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
