# Generated by Django 6.0.2 on 2026-02-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
