# Generated by Django 6.0.2 on 2026-02-14 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itens', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now=True, verbose_name='Data e Hora do Empréstimo')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.item')),
                ('pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
    ]
