# Generated by Django 6.0.2 on 2026-02-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_hora',
            new_name='data_hora_emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_hora_devolucao',
            field=models.DateTimeField(null=True, verbose_name='Data e Hora da Devolução'),
        ),
    ]
