# Generated by Django 6.0.2 on 2026-02-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_rename_data_hora_emprestimo_data_hora_emprestimo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='pessoa_id',
            new_name='pessoa',
        ),
    ]
