# Generated by Django 6.0.2 on 2026-02-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_rename_item_id_emprestimo_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_hora_emprestimo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Empréstimo'),
        ),
    ]
